version: "3.9"
services: 
    db: 
        image: "postgres:13-alpine"
        restart: on-failure
        ports: 
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST}
        networks:
            - to-do
        volumes:
            - postgres:/var/lib/postgresql/data
    pgadmin:
        image: "dpage/pgadmin4"
        restart: on-failure
        ports: 
            - ${PGADMIN_PORT}:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
            - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
        networks:
            - to-do
        volumes:
            - pgadmin:/root/.pgadmin
        depends_on: 
            - db
    server:
        container_name: "api"
        image: "todo/api:latest"
        build: 
            context: ./
            dockerfile: Dockerfile
            ports: 
                - ${API_PORT}:${API_PORT}
            depends_on: 
                - db
            networks:
                - to-do
networks:
    to-do:
        driver: bridge
volumes:
    postgres:
    pgadmin: